#!/bin/sh
#
#   chkconfig: 2345 99 19
#   description: Roomx daemon
# 

DAEMON="wakeup_surveyd"
WAKEUPPATH="/opt/elastix/roomx/"
PARAMETER="-e 100"

start() {
    echo -n "starting up $DAEMON "
    nohup $WAKEUPPATH$DAEMON $PARAMETER & 2>&1 

    if [ "$?" -eq 0 ]; then
        echo " : Done."
    else
        echo " : FAILED."
    fi
}

stop() {
    killall $DAEMON
}

status() {
    killall -0 $DAEMON

    if [ "$?" -eq 0 ]; then
        echo "$DAEMON : Running. "
    else
        echo "$DAEMON : Not Running. "
    fi
}

case "$1" in
    start)
    start
    ;;

    restart)
    stop
    sleep 2
    start
    ;;

    stop)
    stop
    ;;

    status)
    status
    ;;

    *)
    echo "usage : $0 start|restart|stop|status"
    ;;
esac

exit 0